// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { ChampionStatsResponse } from "../champion/champion-stats";
import {
  FreeTierEnum,
  MainPEnum,
  MikeEnum,
  SoloTierEnum,
  SubPEnum,
  TierEnum,
  WantPEnum,
} from "../common";
// May contain unused imports in some cases
// @ts-ignore
import type { GameStyleResponse } from "../game/game-style";

/**
 *
 * @export
 * @interface OtherProfileResponse
 */
export interface OtherProfileResponse {
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  profileImg?: number;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  mike?: MikeEnum;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  gameName?: string;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  soloTier?: SoloTierEnum;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  soloRank?: number;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  soloWinrate?: number;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  freeTier?: FreeTierEnum;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  freeRank?: number;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  freeWinrate?: number;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  mainP?: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  subP?: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof OtherProfileResponse
   */
  wantP?: Array<WantPEnum>;
  /**
   *
   * @type {boolean}
   * @memberof OtherProfileResponse
   */
  isAgree?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OtherProfileResponse
   */
  isBlind?: boolean;
  /**
   *
   * @type {string}
   * @memberof OtherProfileResponse
   */
  loginType?: string;
  /**
   *
   * @type {boolean}
   * @memberof OtherProfileResponse
   */
  blocked?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof OtherProfileResponse
   */
  friend?: boolean;
  /**
   *
   * @type {number}
   * @memberof OtherProfileResponse
   */
  friendRequestMemberId?: number;
  /**
   *
   * @type {Array<GameStyleResponse>}
   * @memberof OtherProfileResponse
   */
  gameStyleResponseList?: Array<GameStyleResponse>;
  /**
   *
   * @type {Array<ChampionStatsResponse>}
   * @memberof OtherProfileResponse
   */
  championStatsResponseList?: Array<ChampionStatsResponse>;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
