
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChatMessageResponse
 */
export interface ChatMessageResponse {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageResponse
     */
    'senderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResponse
     */
    'senderName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageResponse
     */
    'senderProfileImg'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageResponse
     */
    'timestamp'?: number;
}
