// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SystemFlagRequest } from "./system-flag-request";

/**
 *
 * @export
 * @interface ChatCreateRequest
 */
export interface ChatCreateRequest {
  /**
   *
   * @type {string}
   * @memberof ChatCreateRequest
   */
  message: string;
  /**
   *
   * @type {SystemFlagRequest}
   * @memberof ChatCreateRequest
   */
  system?: SystemFlagRequest;
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatCreateResponse
 */
export interface ChatCreateResponse {
  /**
   *
   * @type {number}
   * @memberof ChatCreateResponse
   */
  senderId?: number;
  /**
   *
   * @type {string}
   * @memberof ChatCreateResponse
   */
  senderName?: string;
  /**
   *
   * @type {number}
   * @memberof ChatCreateResponse
   */
  senderProfileImg?: number;
  /**
   *
   * @type {string}
   * @memberof ChatCreateResponse
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof ChatCreateResponse
   */
  createdAt?: string;
  /**
   *
   * @type {number}
   * @memberof ChatCreateResponse
   */
  timestamp?: number;
}
