
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MannerKeywordResponse } from './manner-keyword-response';

/**
 * 
 * @export
 * @interface MannerKeywordListResponse
 */
export interface MannerKeywordListResponse {
    /**
     * 
     * @type {Array<MannerKeywordResponse>}
     * @memberof MannerKeywordListResponse
     */
    'mannerKeywords'?: Array<MannerKeywordResponse>;
}
