
// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MannerInsertRequest
 */
export interface MannerInsertRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof MannerInsertRequest
     */
    'mannerKeywordIdList': Array<number>;
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MannerInsertResponse
 */
export interface MannerInsertResponse {
    /**
     * 
     * @type {number}
     * @memberof MannerInsertResponse
     */
    'mannerRatingId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MannerInsertResponse
     */
    'targetMemberId'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof MannerInsertResponse
     */
    'mannerKeywordIdList'?: Array<number>;
}
