
// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MannerUpdateRequest
 */
export interface MannerUpdateRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof MannerUpdateRequest
     */
    'mannerKeywordIdList': Array<number>;
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MannerUpdateResponse
 */
export interface MannerUpdateResponse {
    /**
     * 
     * @type {number}
     * @memberof MannerUpdateResponse
     */
    'mannerRatingId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MannerUpdateResponse
     */
    'targetMemberId'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof MannerUpdateResponse
     */
    'mannerKeywordIdList'?: Array<number>;
}
