
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockedMemberResponse
 */
export interface BlockedMemberResponse {
    /**
     * 
     * @type {number}
     * @memberof BlockedMemberResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockedMemberResponse
     */
    'profileImg'?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockedMemberResponse
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BlockedMemberResponse
     */
    'blind'?: boolean;
}
