// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse<T = any> {
  /**
   * HTTP status code
   * @type {number}
   * @memberof ApiResponse
   */
  status: number;
  /**
   * Response message
   * @type {string}
   * @memberof ApiResponse
   */
  message: string;
  /**
   * Response code
   * @type {string}
   * @memberof ApiResponse
   */
  code: string;
  /**
   * Response data
   * @type {T}
   * @memberof ApiResponse
   */
  data?: T;
}
