
// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameStyleRequest
 */
export interface GameStyleRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof GameStyleRequest
     */
    'gameStyleIdList'?: Array<number>;
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GameStyleResponse
 */
export interface GameStyleResponse {
    /**
     * 
     * @type {number}
     * @memberof GameStyleResponse
     */
    'gameStyleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GameStyleResponse
     */
    'gameStyleName'?: string;
}
