import type {
  GameModeEnum,
  MainPEnum,
  MikeEnum,
  SubPEnum,
  WantPEnum,
} from "../common";

// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GuestBoardUpdateRequest
 */
export interface GuestBoardUpdateRequest {
  /**
   *
   * @type {number}
   * @memberof GuestBoardUpdateRequest
   */
  boardProfileImage: number;
  /**
   *
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  gameMode: GameModeEnum;
  /**
   *
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  mainP: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  subP: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof GuestBoardUpdateRequest
   */
  wantP: Array<WantPEnum>;
  /**
   * 마이크 사용 여부 (선택)
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  mike?: MikeEnum;
  /**
   *
   * @type {Array<number>}
   * @memberof GuestBoardUpdateRequest
   */
  gameStyles: Array<number>;
  /**
   * 게시글 내용 (선택)
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  contents?: string;
  /**
   * 4-16자의 비밀번호를 입력해주세요
   * @type {string}
   * @memberof GuestBoardUpdateRequest
   */
  password: string;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
