// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatroomResponse
 */
export interface ChatroomResponse {
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  chatroomId?: number;
  /**
   *
   * @type {string}
   * @memberof ChatroomResponse
   */
  uuid?: string;
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  targetMemberId?: number;
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  targetMemberImg?: number;
  /**
   *
   * @type {string}
   * @memberof ChatroomResponse
   */
  targetMemberName?: string;
  /**
   *
   * @type {boolean}
   * @memberof ChatroomResponse
   */
  friend?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChatroomResponse
   */
  blocked?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChatroomResponse
   */
  blind?: boolean;
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  friendRequestMemberId?: number;
  /**
   *
   * @type {string}
   * @memberof ChatroomResponse
   */
  lastMsg?: string;
  /**
   *
   * @type {string}
   * @memberof ChatroomResponse
   */
  lastMsgAt?: string;
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  notReadMsgCnt?: number;
  /**
   *
   * @type {number}
   * @memberof ChatroomResponse
   */
  lastMsgTimestamp?: number;
}
