// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { ChatroomResponse } from "../chatroom/chatroom";

/**
 *
 * @export
 * @interface ChatroomListResponse
 */
export interface ChatroomListResponse {
  /**
   *
   * @type {Array<ChatroomResponse>}
   * @memberof ChatroomListResponse
   */
  chatroomResponseList?: Array<ChatroomResponse>;
  /**
   *
   * @type {number}
   * @memberof ChatroomListResponse
   */
  listSize?: number;
}
