import { MainPEnum, SubPEnum, WantPEnum } from "../common";

// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PositionRequest
 */
export interface PositionRequest {
  /**
   *
   * @type {string}
   * @memberof PositionRequest
   */
  mainP: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof PositionRequest
   */
  subP: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof PositionRequest
   */
  wantP: Array<WantPEnum>;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
