
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BlockedMemberResponse } from './blocked-member-response';

/**
 * 
 * @export
 * @interface BlockListResponse
 */
export interface BlockListResponse {
    /**
     * 
     * @type {Array<BlockedMemberResponse>}
     * @memberof BlockListResponse
     */
    'blockedMemberList'?: Array<BlockedMemberResponse>;
    /**
     * 
     * @type {number}
     * @memberof BlockListResponse
     */
    'listSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockListResponse
     */
    'totalPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockListResponse
     */
    'totalElements'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BlockListResponse
     */
    'isFirst'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BlockListResponse
     */
    'isLast'?: boolean;
}
