
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockResponse
 */
export interface BlockResponse {
    /**
     * 
     * @type {number}
     * @memberof BlockResponse
     */
    'targetMemberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockResponse
     */
    'message'?: string;
}
