// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ReportListResponse } from "../report/report-list";

/**
 *
 * @export
 * @interface ReportPageResponse
 */
export interface ReportPageResponse {
  /**
   *
   * @type {Array<ReportListResponse>}
   * @memberof ReportPageResponse
   */
  reports?: Array<ReportListResponse>;
  /**
   *
   * @type {number}
   * @memberof ReportPageResponse
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof ReportPageResponse
   */
  totalElements?: number;
  /**
   *
   * @type {number}
   * @memberof ReportPageResponse
   */
  currentPage?: number;
}
