
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportListResponse
 */
export interface ReportListResponse {
    /**
     * 
     * @type {number}
     * @memberof ReportListResponse
     */
    'reportId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'fromMemberName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'toMemberName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'reportType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportListResponse
     */
    'createdAt'?: string;
}
