// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReportProcessRequest
 */
export interface ReportProcessRequest {
  /**
   *
   * @type {string}
   * @memberof ReportProcessRequest
   */
  banType: BanTypeEnum;
  /**
   *
   * @type {string}
   * @memberof ReportProcessRequest
   */
  processReason?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum BanTypeEnum {
  NONE = "NONE",
  WARNING = "WARNING",
  BAN_1D = "BAN_1D",
  BAN_3D = "BAN_3D",
  BAN_5D = "BAN_5D",
  BAN_7D = "BAN_7D",
  BAN_1W = "BAN_1W",
  BAN_2W = "BAN_2W",
  BAN_1M = "BAN_1M",
  PERMANENT = "PERMANENT",
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReportProcessResponse
 */
export interface ReportProcessResponse {
  /**
   *
   * @type {number}
   * @memberof ReportProcessResponse
   */
  reportId?: number;
  /**
   *
   * @type {number}
   * @memberof ReportProcessResponse
   */
  targetMemberId?: number;
  /**
   *
   * @type {string}
   * @memberof ReportProcessResponse
   */
  appliedBanType?: AppliedBanTypeEnum;
  /**
   *
   * @type {string}
   * @memberof ReportProcessResponse
   */
  banExpireAt?: string;
  /**
   *
   * @type {string}
   * @memberof ReportProcessResponse
   */
  message?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum AppliedBanTypeEnum {
  NONE = "NONE",
  WARNING = "WARNING",
  BAN_1D = "BAN_1D",
  BAN_3D = "BAN_3D",
  BAN_5D = "BAN_5D",
  BAN_7D = "BAN_7D",
  BAN_1W = "BAN_1W",
  BAN_2W = "BAN_2W",
  BAN_1M = "BAN_1M",
  PERMANENT = "PERMANENT",
}
