export const MATCH_PAGE_DATA = [
  {
    id: 1,
    pathname: "match",
    image: "/assets/images/card/matching.png",
    title: "바로 매칭하기",
    width: "580px",
    height: "285px",
  },
  {
    id: 2,
    pathname: "board",
    image: "/assets/images/card/board.png",
    title: "매칭 게시판에서 찾기",
    width: "580px",
    height: "285px",
  },
];

export const MATCH_TYPE_PAGE_DATA = [
  {
    id: 1,
    type: "gamegoo",
    pathname: "match/game-mode",
    width: "600px",
    height: "276px",
    top: "50%",
    left: "50%",
    title: "겜구 매칭",
    hoverTitle: "빠르게 게임을 시작하고 싶다면",
    sub: "간단한 조건으로 빠르게",
    hoverSub: "간단한 조건만 맞으면 바로 매칭돼요",
    background: "#2E3032",
    hoverBackground: "#5A42EE",
  },
  {
    id: 2,
    type: "custom",
    pathname: "match/game-mode",
    width: "600px",
    height: "276px",
    top: "50%",
    left: "50%",
    title: "맞춤 매칭",
    hoverTitle: "완벽한 게임 친구를 만나고 싶다면",
    sub: "원하는 조건에 딱 맞게",
    hoverSub: "원하는 조건에 맞는 친구를 찾아드려요 *매칭 시간 소요",
    background: "#2E3032",
    hoverBackground: "#5A42EE",
  },
];

export const GAME_MODE_PAGE_DATA = [
  {
    id: 1,
    rank: "personal",
    pathname: "profile",
    width: "296px",
    height: "156px",
    top: "50%",
    left: "50%",
    title: "빠른 대전",
  },
  {
    id: 2,
    rank: "free",
    pathname: "profile",
    width: "296px",
    height: "156px",
    top: "50%",
    left: "50%",
    title: "솔로 랭크",
  },
  {
    id: 3,
    rank: "fast",
    pathname: "profile",
    width: "296px",
    height: "156px",
    top: "50%",
    left: "50%",
    title: "자유 랭크",
  },
  {
    id: 4,
    rank: "wind",
    pathname: "profile",
    width: "296px",
    height: "156px",
    top: "50%",
    left: "50%",
    title: "칼바람",
  },
];
