
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatMessageListResponse } from './chat-message-list-response';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemFlagResponse } from './system-flag-response';

/**
 * 
 * @export
 * @interface EnterChatroomResponse
 */
export interface EnterChatroomResponse {
    /**
     * 
     * @type {string}
     * @memberof EnterChatroomResponse
     */
    'uuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof EnterChatroomResponse
     */
    'memberId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EnterChatroomResponse
     */
    'gameName'?: string;
    /**
     * 
     * @type {number}
     * @memberof EnterChatroomResponse
     */
    'memberProfileImg'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EnterChatroomResponse
     */
    'friend'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnterChatroomResponse
     */
    'blocked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnterChatroomResponse
     */
    'blind'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EnterChatroomResponse
     */
    'friendRequestMemberId'?: number;
    /**
     * 
     * @type {SystemFlagResponse}
     * @memberof EnterChatroomResponse
     */
    'system'?: SystemFlagResponse;
    /**
     * 
     * @type {ChatMessageListResponse}
     * @memberof EnterChatroomResponse
     */
    'chatMessageListResponse'?: ChatMessageListResponse;
}
