import {
  MikeEnum,
  GameModeEnum,
  MainPEnum,
  SubPEnum,
  WantPEnum,
  TierEnum,
} from "../common";

// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BoardInsertRequest
 */
export interface BoardInsertRequest {
  /**
   *
   * @type {number}
   * @memberof BoardInsertRequest
   */
  boardProfileImage: number;
  /**
   *
   * @type {string}
   * @memberof BoardInsertRequest
   */
  gameMode: GameModeEnum;
  /**
   *
   * @type {string}
   * @memberof BoardInsertRequest
   */
  mainP: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof BoardInsertRequest
   */
  subP: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof BoardInsertRequest
   */
  wantP: Array<WantPEnum>;
  /**
   * 마이크 사용 여부
   * @type {string}
   * @memberof BoardInsertRequest
   */
  mike?: MikeEnum;
  /**
   *
   * @type {Array<number>}
   * @memberof BoardInsertRequest
   */
  gameStyles: Array<number>;
  /**
   * 게시글 내용 (선택)
   * @type {string}
   * @memberof BoardInsertRequest
   */
  contents?: string;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BoardInsertResponse
 */
export interface BoardInsertResponse {
  /**
   *
   * @type {number}
   * @memberof BoardInsertResponse
   */
  boardId?: number;
  /**
   *
   * @type {number}
   * @memberof BoardInsertResponse
   */
  memberId?: number;
  /**
   *
   * @type {number}
   * @memberof BoardInsertResponse
   */
  profileImage?: number;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  gameName?: string;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  tier?: TierEnum;
  /**
   *
   * @type {number}
   * @memberof BoardInsertResponse
   */
  rank?: number;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  gameMode?: GameModeEnum;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  mainP?: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  subP?: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof BoardInsertResponse
   */
  wantP?: Array<WantPEnum>;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  mike?: MikeEnum;
  /**
   *
   * @type {Array<number>}
   * @memberof BoardInsertResponse
   */
  gameStyles?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof BoardInsertResponse
   */
  contents?: string;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
