// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import {
  FreeTierEnum,
  GameModeEnum,
  MainPEnum,
  MikeEnum,
  SoloTierEnum,
  SubPEnum,
  TierEnum,
  WantPEnum,
} from "../common";

import type { ChampionStatsResponse } from "../champion/champion-stats";
// May contain unused imports in some cases
// @ts-ignore
import type { MemberRecentStatsResponse } from "../member/member-recent-stats";

/**
 *
 * @export
 * @interface BoardListResponse
 */
export interface BoardListResponse {
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  boardId?: number;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  memberId?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  gameName?: string;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  mainP?: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  subP?: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof BoardListResponse
   */
  wantP?: Array<WantPEnum>;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  mike?: MikeEnum;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  contents?: string;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  boardProfileImage?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  createdAt?: string;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  profileImage?: number;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  mannerLevel?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  tier?: TierEnum;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  rank?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  gameMode?: GameModeEnum;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  winRate?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  bumpTime?: string;
  /**
   *
   * @type {Array<ChampionStatsResponse>}
   * @memberof BoardListResponse
   */
  championStatsResponseList?: Array<ChampionStatsResponse>;
  /**
   *
   * @type {MemberRecentStatsResponse}
   * @memberof BoardListResponse
   */
  memberRecentStats?: MemberRecentStatsResponse;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  freeTier?: FreeTierEnum;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  freeRank?: number;
  /**
   *
   * @type {string}
   * @memberof BoardListResponse
   */
  soloTier?: SoloTierEnum;
  /**
   *
   * @type {number}
   * @memberof BoardListResponse
   */
  soloRank?: number;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
