// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { BoardListResponse } from "./board-list-response";

/**
 *
 * @export
 * @interface BoardCursorResponse
 */
export interface BoardCursorResponse {
  /**
   *
   * @type {Array<BoardListResponse>}
   * @memberof BoardCursorResponse
   */
  boards?: Array<BoardListResponse>;
  /**
   *
   * @type {boolean}
   * @memberof BoardCursorResponse
   */
  hasNext?: boolean;
  /**
   *
   * @type {string}
   * @memberof BoardCursorResponse
   */
  nextCursor?: string;
  /**
   *
   * @type {number}
   * @memberof BoardCursorResponse
   */
  cursorId?: number;
}
