import { TierEnum } from "../common";

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MyBoardListResponse
 */
export interface MyBoardListResponse {
  /**
   *
   * @type {number}
   * @memberof MyBoardListResponse
   */
  boardId?: number;
  /**
   *
   * @type {number}
   * @memberof MyBoardListResponse
   */
  memberId?: number;
  /**
   *
   * @type {number}
   * @memberof MyBoardListResponse
   */
  profileImage?: number;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  gameName?: string;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  tier?: TierEnum;
  /**
   *
   * @type {number}
   * @memberof MyBoardListResponse
   */
  rank?: number;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  contents?: string;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof MyBoardListResponse
   */
  bumpTime?: string;
  /**
   *
   * @type {number}
   * @memberof MyBoardListResponse
   */
  mannerLevel?: number;
}

/**
 * @export
 * @enum {string}
 */
