// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { MyBoardListResponse } from "./my-board-list-response";

/**
 *
 * @export
 * @interface MyBoardResponse
 */
export interface MyBoardResponse {
  /**
   *
   * @type {number}
   * @memberof MyBoardResponse
   */
  totalPage?: number;
  /**
   *
   * @type {number}
   * @memberof MyBoardResponse
   */
  totalCount?: number;
  /**
   *
   * @type {Array<MyBoardListResponse>}
   * @memberof MyBoardResponse
   */
  myBoards?: Array<MyBoardListResponse>;
}
