
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChampionStatsResponse
 */
export interface ChampionStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'championId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChampionStatsResponse
     */
    'championName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'winRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'wins'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'games'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'csPerMinute'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'kda'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'kills'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'deaths'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChampionStatsResponse
     */
    'assists'?: number;
}
