// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { MatchingMemberInfoResponse } from "../matching/matching-member-info";
// May contain unused imports in some cases
// @ts-ignore
import type { PriorityValue } from "./priority-value";

/**
 *
 * @export
 * @interface PriorityListResponse
 */
export interface PriorityListResponse {
  /**
   *
   * @type {Array<PriorityValue>}
   * @memberof PriorityListResponse
   */
  myPriorityList?: Array<PriorityValue>;
  /**
   *
   * @type {Array<PriorityValue>}
   * @memberof PriorityListResponse
   */
  otherPriorityList?: Array<PriorityValue>;
  /**
   *
   * @type {MatchingMemberInfoResponse}
   * @memberof PriorityListResponse
   */
  myMatchingInfo?: MatchingMemberInfoResponse;
}
