// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { NotificationResponse } from "../notification/notification";

/**
 *
 * @export
 * @interface NotificationPageListResponse
 */
export interface NotificationPageListResponse {
  /**
   *
   * @type {Array<NotificationResponse>}
   * @memberof NotificationPageListResponse
   */
  notificationList?: Array<NotificationResponse>;
  /**
   *
   * @type {number}
   * @memberof NotificationPageListResponse
   */
  listSize?: number;
  /**
   *
   * @type {number}
   * @memberof NotificationPageListResponse
   */
  totalPage?: number;
  /**
   *
   * @type {number}
   * @memberof NotificationPageListResponse
   */
  totalElements?: number;
  /**
   *
   * @type {boolean}
   * @memberof NotificationPageListResponse
   */
  isFirst?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof NotificationPageListResponse
   */
  isLast?: boolean;
}
