
// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationResponse
 */
export interface NotificationResponse {
    /**
     * 
     * @type {number}
     * @memberof NotificationResponse
     */
    'notificationId'?: number;
    /**
     * 
     * @type {number}
     * @memberof NotificationResponse
     */
    'notificationType'?: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'pageUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResponse
     */
    'read'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'createdAt'?: string;
}
