// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MemberRecentStatsResponse
 */
export interface MemberRecentStatsResponse {
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recTotalWins?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recTotalLosses?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recWinRate?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recAvgKDA?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recAvgKills?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recAvgDeaths?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recAvgAssists?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recAvgCsPerMinute?: number;
  /**
   *
   * @type {number}
   * @memberof MemberRecentStatsResponse
   */
  recTotalCs?: number;
}
