/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";

import type { ApiResponseListLong } from "../models/index";

export interface GetFriendIdsRequest {
  memberId: number;
}

/**
 * FriendInternalApi - interface
 *
 * @export
 * @interface FriendInternalApiInterface
 */
export interface FriendInternalApiInterface {
  /**
   * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
   * @summary 모든 친구 id 조회 API
   * @param {number} memberId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FriendInternalApiInterface
   */
  getFriendIdsRaw(
    requestParameters: GetFriendIdsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ApiResponseListLong>>;

  /**
   * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
   * 모든 친구 id 조회 API
   */
  getFriendIds(
    requestParameters: GetFriendIdsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ApiResponseListLong>;
}

/**
 *
 */
export class FriendInternalApi
  extends runtime.BaseAPI
  implements FriendInternalApiInterface
{
  /**
   * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
   * 모든 친구 id 조회 API
   */
  async getFriendIdsRaw(
    requestParameters: GetFriendIdsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ApiResponseListLong>> {
    if (requestParameters["memberId"] == null) {
      throw new runtime.RequiredError(
        "memberId",
        'Required parameter "memberId" was null or undefined when calling getFriendIds().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("JWT TOKEN", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v2/internal/{memberId}/friend/ids`.replace(
          `{${"memberId"}}`,
          encodeURIComponent(String(requestParameters["memberId"]))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * 해당 회원의 모든 친구 id 목록을 조회하는 API 입니다. 정렬 기능 없음, socket서버용 API입니다.
   * 모든 친구 id 조회 API
   */
  async getFriendIds(
    requestParameters: GetFriendIdsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ApiResponseListLong> {
    const response = await this.getFriendIdsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
