/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseLong,
  ApiResponseObject,
  ApiResponseString,
  RiotUserInfo,
} from '../models/index';

export interface GetMemberIdRequest {
    riotUserInfo: RiotUserInfo;
}

export interface GetTestAccessTokenRequest {
    memberId: number;
}

export interface JoinTestRequest {
    riotUserInfo: RiotUserInfo;
}

export interface RefreshStatsRequest {
    memberId: number;
}

/**
 * HomeApi - interface
 * 
 * @export
 * @interface HomeApiInterface
 */
export interface HomeApiInterface {
    /**
     * 예외를 발생시켜 테스트합니다.
     * @summary 에러 테스트
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    errorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>>;

    /**
     * 예외를 발생시켜 테스트합니다.
     * 에러 테스트
     */
    error(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject>;

    /**
     * 
     * @summary 소환사명과 태그로 해당 회원 id 조회
     * @param {RiotUserInfo} riotUserInfo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    getMemberIdRaw(requestParameters: GetMemberIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseLong>>;

    /**
     * 소환사명과 태그로 해당 회원 id 조회
     */
    getMemberId(requestParameters: GetMemberIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseLong>;

    /**
     * 테스트용으로 access token을 발급받을 수 있는 API 입니다.
     * @summary memberId로 access token 발급 API
     * @param {number} memberId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    getTestAccessTokenRaw(requestParameters: GetTestAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>>;

    /**
     * 테스트용으로 access token을 발급받을 수 있는 API 입니다.
     * memberId로 access token 발급 API
     */
    getTestAccessToken(requestParameters: GetTestAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString>;

    /**
     * health check를 위한 API 입니다.
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>>;

    /**
     * health check를 위한 API 입니다.
     * Health Check
     */
    healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString>;

    /**
     * API 서비스 상태를 확인합니다.
     * @summary 홈 엔드포인트
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    homeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>>;

    /**
     * API 서비스 상태를 확인합니다.
     * 홈 엔드포인트
     */
    home(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString>;

    /**
     * 
     * @summary 라이엇 계정 회원 가입
     * @param {RiotUserInfo} riotUserInfo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    joinTestRaw(requestParameters: JoinTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>>;

    /**
     * 라이엇 계정 회원 가입
     */
    joinTest(requestParameters: JoinTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject>;

    /**
     * 
     * @summary 챔피언 전적 통계 갱신
     * @param {number} memberId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApiInterface
     */
    refreshStatsRaw(requestParameters: RefreshStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>>;

    /**
     * 챔피언 전적 통계 갱신
     */
    refreshStats(requestParameters: RefreshStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString>;

}

/**
 * 
 */
export class HomeApi extends runtime.BaseAPI implements HomeApiInterface {

    /**
     * 예외를 발생시켜 테스트합니다.
     * 에러 테스트
     */
    async errorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/errortest`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 예외를 발생시켜 테스트합니다.
     * 에러 테스트
     */
    async error(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.errorRaw(initOverrides);
        return await response.value();
    }

    /**
     * 소환사명과 태그로 해당 회원 id 조회
     */
    async getMemberIdRaw(requestParameters: GetMemberIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseLong>> {
        if (requestParameters['riotUserInfo'] == null) {
            throw new runtime.RequiredError(
                'riotUserInfo',
                'Required parameter "riotUserInfo" was null or undefined when calling getMemberId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/home/getMemberId`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['riotUserInfo'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 소환사명과 태그로 해당 회원 id 조회
     */
    async getMemberId(requestParameters: GetMemberIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseLong> {
        const response = await this.getMemberIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 테스트용으로 access token을 발급받을 수 있는 API 입니다.
     * memberId로 access token 발급 API
     */
    async getTestAccessTokenRaw(requestParameters: GetTestAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling getTestAccessToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/home/token/{memberId}`.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 테스트용으로 access token을 발급받을 수 있는 API 입니다.
     * memberId로 access token 발급 API
     */
    async getTestAccessToken(requestParameters: GetTestAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString> {
        const response = await this.getTestAccessTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * health check를 위한 API 입니다.
     * Health Check
     */
    async healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/healthcheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * health check를 위한 API 입니다.
     * Health Check
     */
    async healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString> {
        const response = await this.healthcheckRaw(initOverrides);
        return await response.value();
    }

    /**
     * API 서비스 상태를 확인합니다.
     * 홈 엔드포인트
     */
    async homeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/home`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * API 서비스 상태를 확인합니다.
     * 홈 엔드포인트
     */
    async home(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString> {
        const response = await this.homeRaw(initOverrides);
        return await response.value();
    }

    /**
     * 라이엇 계정 회원 가입
     */
    async joinTestRaw(requestParameters: JoinTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseObject>> {
        if (requestParameters['riotUserInfo'] == null) {
            throw new runtime.RequiredError(
                'riotUserInfo',
                'Required parameter "riotUserInfo" was null or undefined when calling joinTest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/home/join`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['riotUserInfo'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 라이엇 계정 회원 가입
     */
    async joinTest(requestParameters: JoinTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseObject> {
        const response = await this.joinTestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 챔피언 전적 통계 갱신
     */
    async refreshStatsRaw(requestParameters: RefreshStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseString>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling refreshStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT TOKEN", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/home/refresh/stats/{memberId}`.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 챔피언 전적 통계 갱신
     */
    async refreshStats(requestParameters: RefreshStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseString> {
        const response = await this.refreshStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
