// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SystemFlagRequest
 */
export interface SystemFlagRequest {
  /**
   *
   * @type {number}
   * @memberof SystemFlagRequest
   */
  flag: number;
  /**
   *
   * @type {number}
   * @memberof SystemFlagRequest
   */
  boardId: number;
}

// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SystemFlagResponse
 */
export interface SystemFlagResponse {
  /**
   *
   * @type {number}
   * @memberof SystemFlagResponse
   */
  flag?: number;
  /**
   *
   * @type {number}
   * @memberof SystemFlagResponse
   */
  boardId?: number;
}
