import type {
  GameModeEnum,
  MainPEnum,
  MikeEnum,
  SubPEnum,
  WantPEnum,
} from "../common";

// Request types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InitializingMatchingRequest
 */
export interface InitializingMatchingRequest {
  /**
   *
   * @type {string}
   * @memberof InitializingMatchingRequest
   */
  gameMode: GameModeEnum;
  /**
   *
   * @type {string}
   * @memberof InitializingMatchingRequest
   */
  mike: MikeEnum;
  /**
   *
   * @type {string}
   * @memberof InitializingMatchingRequest
   */
  matchingType: MatchingTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InitializingMatchingRequest
   */
  mainP?: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof InitializingMatchingRequest
   */
  subP?: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof InitializingMatchingRequest
   */
  wantP?: Array<WantPEnum>;
  /**
   *
   * @type {Array<number>}
   * @memberof InitializingMatchingRequest
   */
  gameStyleIdList?: Array<number>;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
export enum MatchingTypeEnum {
  BASIC = "BASIC",
  PRECISE = "PRECISE",
}
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
