// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
// May contain unused imports in some cases
// @ts-ignore
import type { MatchingMemberInfoResponse } from "../matching/matching-member-info";

/**
 *
 * @export
 * @interface MatchingFoundResponse
 */
export interface MatchingFoundResponse {
  /**
   *
   * @type {MatchingMemberInfoResponse}
   * @memberof MatchingFoundResponse
   */
  myMatchingInfo?: MatchingMemberInfoResponse;
  /**
   *
   * @type {MatchingMemberInfoResponse}
   * @memberof MatchingFoundResponse
   */
  targetMatchingInfo?: MatchingMemberInfoResponse;
}
