// Response types
/* tslint:disable */
/* eslint-disable */
/**
 * Gamegoo V2 API
 * Gamegoo V2 API 명세서
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import {
  FreeTierEnum,
  GameModeEnum,
  MainPEnum,
  MikeEnum,
  SoloTierEnum,
  SubPEnum,
  TierEnum,
  WantPEnum,
} from "../common";

import type { GameStyleResponse } from "../game/game-style";

/**
 *
 * @export
 * @interface MatchingMemberInfoResponse
 */
export interface MatchingMemberInfoResponse {
  /**
   *
   * @type {number}
   * @memberof MatchingMemberInfoResponse
   */
  memberId?: number;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  matchingUuid?: string;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  gameName?: string;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  tag?: string;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  soloTier?: SoloTierEnum;
  /**
   *
   * @type {number}
   * @memberof MatchingMemberInfoResponse
   */
  soloRank?: number;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  freeTier?: FreeTierEnum;
  /**
   *
   * @type {number}
   * @memberof MatchingMemberInfoResponse
   */
  freeRank?: number;
  /**
   *
   * @type {number}
   * @memberof MatchingMemberInfoResponse
   */
  mannerLevel?: number;
  /**
   *
   * @type {number}
   * @memberof MatchingMemberInfoResponse
   */
  profileImg?: number;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  gameMode?: GameModeEnum;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  mainP?: MainPEnum;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  subP?: SubPEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof MatchingMemberInfoResponse
   */
  wantP?: Array<WantPEnum>;
  /**
   *
   * @type {string}
   * @memberof MatchingMemberInfoResponse
   */
  mike?: MikeEnum;
  /**
   *
   * @type {Array<GameStyleResponse>}
   * @memberof MatchingMemberInfoResponse
   */
  gameStyleResponseList?: Array<GameStyleResponse>;
}

/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
/**
 * @export
 * @enum {string}
 */
